#{{ if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
## Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
##
## WSO2 LLC. licenses this file to you under the Apache License,
## Version 2.0 (the "License"); you may not use this file except
## in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied. See the License for the
## specific language governing permissions and limitations
## under the License.
#
#{{- $username := .Values.wso2.subscription.username }}
#{{- $password := .Values.wso2.subscription.password }}
#{{- $email := .Values.wso2.subscription.username }}
#{{- $regId := "docker.wso2.com" }}
#{{- $auth := printf "%s:%s" $username $password | b64enc }}
#{{- $files := .Files }}
#
#apiVersion: {{ .Values.k8sKindAPIVersions.secret }}
#kind: Secret
#metadata:
#  name: {{ template "..fullname" . }}-wso2-private-registry-creds
#  namespace: {{ .Release.Namespace }}
#type: kubernetes.io/dockerconfigjson
#data:
#  .dockerconfigjson: {{ $files.Get "confs/auth.json" | replace "reg.id" $regId | replace "reg.username" $username | replace "reg.password" $password | replace "reg.email" $email | replace "reg.auth" $auth | b64enc }}
#{{ end }}

apiVersion: {{ .Values.k8sKindAPIVersions.secret }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhc2hpMTk5MyIsInBhc3N3b3JkIjoiMXFhejJ3c3hBIyIsImVtYWlsIjoiYXNoaXJ3YWRhQHdzbzIuY29tIiwiYXV0aCI6IllYTm9hVEU1T1RNNk1YRmhlakozYzNoQkl3PT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2025-07-02T04:49:37Z"
  name: regcred
  namespace: {{ .Release.Namespace }}
  resourceVersion: "4202346"
  uid: 08c2ec44-7488-4d22-8245-5c472776e8ec
type: kubernetes.io/dockerconfigjson